# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0003_auto_20171113_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='groupes_de_partage',
            field=models.ManyToManyField(blank=True, to='spot.Groupe'),
        ),
    ]
